# .github/workflows/macos.yml
name: macOS DMG OS12
on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: Firebay-MacOS12
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          brew update
          brew install cmake ninja qt@6
          echo "$(brew --prefix qt@6)/bin" >> "$GITHUB_PATH"
      - name: Configure & Build
        run: |
          qt_prefix=$(brew --prefix qt@6)
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$qt_prefix"
          ninja -C build
      - name: Deploy Qt into .app bundle
        run: |
          qt_prefix=$(brew --prefix qt@6)
          "$qt_prefix/bin/macdeployqt" build/fireminipro.app -verbose=2
      - name: Ad-hoc sign app bundle
        run: |
          xattr -cr build/fireminipro.app
          codesign --force --deep --sign - build/fireminipro.app
      - name: Create DMG
        run: |
          mkdir -p dist
          cp -R build/fireminipro.app dist/
          hdiutil create -volname FireMinipro -srcfolder dist -ov -format UDZO build/fireminipro_macos12.dmg
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
