# .github/workflows/macos.yml
name: macOS DMG
on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          brew update
          brew install cmake ninja qt@6
          echo "$(brew --prefix qt@6)/bin" >> "$GITHUB_PATH"
      - name: Configure & Build
        run: |
          qt_prefix=$(brew --prefix qt@6)
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$qt_prefix"
          ninja -C build
      - name: Deploy Qt into .app and package DMG
        run: |
          qt_prefix=$(brew --prefix qt@6)
          "$qt_prefix/bin/macdeployqt" build/fireminipro.app -verbose=2 -dmg
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
