# .github/workflows/macos12.yml
name: macOS DMG OS12
on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: Firebay-MacOS12
    env:
      MACOSX_DEPLOYMENT_TARGET: "12.0"
      QT_HOME: "/Users/firebay/Qt/6.9.3/macos"
    steps:
      - uses: actions/checkout@v4
      - name: Configure & Build (x86_64)
        run: |
          export PATH="$QT_HOME/bin:$PATH"
          arch -x86_64 cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_PREFIX_PATH="$QT_HOME" -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0
          arch -x86_64 ninja -C build
      - name: Deploy Qt into .app bundle
        run: |
          export PATH="$QT_HOME/bin:$PATH"
          arch -x86_64 "$QT_HOME/bin/macdeployqt" build/fireminipro.app -verbose=2
      - name: Ad-hoc sign app bundle
        run: |
          arch -x86_64 xattr -cr build/fireminipro.app
          arch -x86_64 codesign --force --deep --sign - build/fireminipro.app
      - name: Create DMG
        run: |
          mkdir -p dist
          cp -R build/fireminipro.app dist/
          arch -x86_64 hdiutil create -volname FireMinipro -srcfolder dist -ov -format UDZO build/fireminipro_intel.dmg
      - name: Get latest tag (for manual trigger)
        id: get_tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          latest_tag=$(git tag --sort=-creatordate | head -n 1)
          echo "tag_name=$latest_tag" >> $GITHUB_OUTPUT
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.dmg
          tag_name: ${{ github.event_name == 'workflow_dispatch' && steps.get_tag.outputs.tag_name || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
